#!/bin/bash
julien@ubuntu:/$ echo -e 'C#\nC\nJavascript\nPerl\nPHP\nPHP\nASP\nR\nGo\nC#\nC++\nR\nPerl\nJavascript\nJavascript\nPython\nJavascript\nJavascript\nJavascript\nJava\nJava\nPython\nJavascript\nJavascript\nJavascript\nASP' > list
julien@ubuntu:/$ cat list 
C#
C
Javascript
Perl
PHP
PHP
ASP
R
Go
C#
C++
R
Perl
Javascript
Javascript
Python
Javascript
Javascript
Javascript
Java
Java
Python
Javascript
Javascript
Javascript
ASP
julien@ubuntu:/$ cat list | ./0-unique 
C
C++
Go
julien@ubuntu:/$ 
